import useMatrixStore from "../store/useMatrixStore";

export default function generatePlugAndPlay() {
  const { rows, cols, frames, wiring, controller } = useMatrixStore.getState();

  return `
// ------------------------------------------------------------
// Auto-Generated Plug and Play Firmware
// Generated by LED Matrix Builder
// ------------------------------------------------------------

#include <FastLED.h>

#define LED_PIN 5
#define NUM_ROWS ${rows}
#define NUM_COLS ${cols}
#define NUM_LEDS (NUM_ROWS * NUM_COLS)

CRGB leds[NUM_LEDS];

// ------------------------
// Wiring Pattern
// ------------------------
int mapIndex(int r, int c) {
  // ${wiring}
  
  // Progressive
  if ("${wiring}" == "progressive") {
    return r * NUM_COLS + c;
  }

  // Reverse Progressive
  if ("${wiring}" == "reverse_progressive") {
    return r * NUM_COLS + (NUM_COLS - 1 - c);
  }

  // Serpentine
  if ("${wiring}" == "serpentine") {
    return (r % 2 == 0)
      ? r * NUM_COLS + c
      : r * NUM_COLS + (NUM_COLS - 1 - c);
  }

  // Default fallback
  return r * NUM_COLS + c;
}

// ------------------------
// Animation Frames
// ------------------------
const uint32_t FRAMES[][NUM_ROWS * NUM_COLS] = {
${frames
  .map(
    (frame) =>
      "  { " +
      frame.map((px) => `0x${px.replace("#", "")}`).join(", ") +
      " },"
  )
  .join("\n")}
};

int currentFrame = 0;

// ------------------------
// Setup
// ------------------------
void setup() {
  FastLED.addLeds<WS2812, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.clear();
  FastLED.show();
}

// ------------------------
// Loop
// ------------------------
void loop() {
  for (int r = 0; r < NUM_ROWS; r++) {
    for (int c = 0; c < NUM_COLS; c++) {
      int idx = mapIndex(r, c);
      leds[idx] = FRAMES[currentFrame][r * NUM_COLS + c];
    }
  }

  FastLED.show();
  delay(100);

  currentFrame++;
  if (currentFrame >= ${frames.length}) currentFrame = 0;
}  
`;
}
